# THE CONFIG FILE
# Circa February 2024

autoMaxSpeed = 1
autoMaxAcceleration = 0.5

driveMaxSpeed = 3.0
maxAngularSpeed = 3.14159
slowScaler = 0.2
boostScaler = 2.0

driveP = 0.0
driveI = 0.0
driveD = 0.0
driveIZone = 0.0
driveFF = 3.25

# Drivetrain turning offset constants
FLModuleOffset = 0.157329
FRModuleOffset = 0.345974
BRModuleOffset = 0.823048
BLModuleOffset = 0.329460

turnP = 0.1
turnI = 0.0
turnD = 0.0
turnIZone = 0
turnFF = 0

turningMinOutput = -1
turningMaxOutput = 1

autoAimP = 1
autoAimI = 0
autoAimD = 0
autoAimThreshold = 1

# Intake
pivotEncoderOffset = 0.0

groundPivotAngle = 0.0
sourcePivotAngle = 0.0
intakeAmpPivotAngle = 0.0
stowPivotAngle = 0.0

intakeSpeed = 0.0
ejectSpeed = 0.0
feedShooterSpeed = 0.0

intakePivotMotorP = 0.0
intakePivotMotorI = 0.0
intakePivotMotorD = 0.0

# Shooter
shooterMotorP = 0.0
shooterMotorI = 0.0
shooterMotorD = 0.0

shooterMinOutput = 0.0
shooterMaxOutput = 1.0

shooterPivotMotorP = 0.0
shooterPivotMotorI = 0.0
shooterPivotMotorD = 0.0

lowPivotAngle = 0.0
shooterAmpPivotAngle = 0.0
speakerPivotAngle = 0.0

# Climber
climberVelocity = 0.25 # m/s